/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class B1 */

#ifndef _Included_B1
#define _Included_B1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     B1
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_B1_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
